apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: calculator-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calculator-app

  template:
    metadata:
      labels:
        app: calculator-app

    spec:
      volumes:
        - name: # storage-class-name
          persistentVolumeClaim:
            claimName: # pvc-name
  
      containers:
      - name: # container_name1
        image: nginx # which image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: # storage-class-name
          mountPath: /tmp/persistent  # Path inside the container where the volume will be mounted
      - name: # container_name2
        image: tomcat # which image
        ports:
        - containerPort: 5001