# How to assign a single volume to specific container in a pod

apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: calculator-app
spec:
  selector:
    matchLabels:
      app: calculator-app
  strategy:
    type: RollingUpdate
  replicas: 1
  
  template:
    metadata:
      labels:
        app: calculator-app

    spec:
      volumes:
      - name: # volume_name
        hostPath:
         path: /mnt/data # path on the host
         type: Directory # type of hostPath

      containers:
      - name: # container_name1
        image: nginx # which image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: # volume_name
          mountPath: /var/nginx-data or "/var/nginx-data" # path inside the container

      - name: # container_name2
        image: tomcat # which image
        ports:
        - containerPort: 5001