apiVersion: v1
kind: Service
metadata:
  name: nginx-service # The name of the Service
spec:
  type: None
  ports:
  - port: 80
    name: web
  clusterIP: None # This makes the Service headless
  selector:
    app: nginx # Selects Pods with the label "app: nginx"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx-service" # Must match the headless Service name
  replicas: 2 # Desired number of Pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www # Refers to the PersistentVolumeClaim template below
          mountPath: /usr/share/nginx/html # Mount path within the container
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi # Requests 1Gi of storage for each Pod
