apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   annotations:
#     kubernetes.io/enforce-mountable-secrets: "true"
#   name: my-serviceaccount
#   namespace: my-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
