apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: calculator-app
spec:
  selector:
    matchLabels:
      app: calculator-app
  strategy:
    type: RollingUpdate
  replicas: 1

  template:
    metadata:
      labels:
        app: calculator-app

    spec:
      containers:
      - name: # container_name
        image: # which image
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: SECRET_KEY # environment variable name
          valueFrom:
            secretKeyRef:
              name: # secret-name
              key: SECRET_KEY # environment variable name
              # we give single secret key like using env variable or we can give all keys using envFrom 
        envFrom:
        - secretRef:
            name: # secret-name