apiVersion: v1
kind: Secret
metadata:
  name: # secret-name
type: Opaque
data:
  username: YMRtaW4=          # echo -n "admin" | base64
  password: UGE1NXcwcmQ==     # echo -n "password" | base64

# to see base64 values
# kubectl get secret secret-name -o jsonpath='{.data.username}'
#     output > YMRtaW4=heman
# kubectl get secret secret-name -o jsonpath='{.data.username}' | base64 --decode
#     output > heman
